name: Trigger Vercel Deploy

on:
  push:
    branches:
      - main
   
jobs:
  trigger-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create deployment trigger commit
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          # Create an empty commit
          git commit --allow-empty -m "trigger: Vercel deployment for collaborator commit"
          # Push using GitHub token
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push origin ${{ github.ref_name }}
