
name: Trigger Vercel Deploy 

on:
  push:
    branches:
      - main  # Change this to your default branch if different

jobs:
  empty-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: github.event.pusher.name != github.repository_owner
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Create empty commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit --allow-empty -m "trigger: Auto commit to trigger deployment"
          git push origin ${{ github.ref_name }}

